### PR TITLE
master

### PR DESCRIPTION
**Pull request by IgorGanapolsky**

### CODE REVIEW

**Comment by keyboardsurfer** [comment]
Hi Igor. Thanks for the PR. What's the reason for updating the versions at this point?
Any new features you're planning on accessing?
Without further context this commit does not justify the version update IMO.

**Comment by IgorGanapolsky** [comment]
Don't you always want the latest version of Google's support lib??  With bug fixes and all.  I thought you work for Google.  LOL.

**Comment by keyboardsurfer** [comment]
There are currently no bugs filed against Topeka that would be fixed by updates of the dependencies in your PR.
Even though the new versions introduced new functionality, this is nothing that is currently being used within Topeka. So I don't deem the updates critical enough to perform this for the sole purpose of having updated dependencies.

**Comment by piotrek1543** [comment]
@IgorGanapolsky before you make a pull request, please check the closed ones.
I made the same PR and it's closed. @keyboardsurfer, isn't it? :-)

**Pull request closed without merging**
