### PR TITLE
int array better should be called "intArray"

### PR DESCRIPTION
**Pull request by alexrm**

### CODE REVIEW

**Comment by alexrm** [comment]
I signed it!

**Comment by alexrm** [comment]
I signed it!

**Comment by keyboardsurfer** [comment]
Please make sure to select "Any other Google project" when signing the CLA.

**Comment by alexrm** [comment]
Done

**Comment by keyboardsurfer** [comment]
Rebased to master and released with b84496a1b7290b5a55849b4dc3498ffe32297226.

**Pull request closed without merging**
