### PR TITLE
Fixed keyboard related issue

### PR DESCRIPTION
**Pull request by ShreyashPromact**
Keyboard is not hiding even if user enter the answers and navigate to another question. In that case User is not able to select answer of other questions.
That issue is resolved now.

### CODE REVIEW

**Comment by ShreyashPromact** [comment]
@keyboardsurfer 
please check updated commit.

**Comment by ShreyashPromact** [comment]
@keyboardsurfer 
Should i need to pull request again or the update I have done is enough?

**Comment by keyboardsurfer** [comment]
The update is good to go if you want to keep both commits in history. Otherwise feel free to create a new PR with a squashed version.

**Comment by ShreyashPromact** [comment]
@keyboardsurfer 
Why it will remain as history. Will it not be getting approved? If not then what is the reason. I would like to know about that. If My commits are proper then i suppose it to be merged.

Thanks.

Sincerely,
Shreyash

**Comment by keyboardsurfer** [comment]
Multiple commits that build upon each other are called "commit history", so I guess that we have a slight misunderstanding here.
I appreciate your contribution and will merge it soon.

**Comment by ShreyashPromact** [comment]
Ok. Thanks for reply. I will wait for updates.

Sincerely,
Shreyash

**Comment by ShreyashPromact** [comment]
@keyboardsurfer 
Just want to know, how much time normally google take to merge the changes if it is proper as per the coding guidelines?

**Comment by keyboardsurfer** [comment]
I just found an interesting [read on this topic](http://www.gousios.gr/blog/How-do-project-owners-use-pull-requests-on-Github). But answering the underlying question: Rest assured, I value your contribution and will merge it soon.

**Comment by keyboardsurfer** [comment]
Please excuse the merge delay. As you may have seen I just pushed [a major update](https://github.com/googlesamples/android-topeka/commit/79d6010d4defe4ce865b8672535dc7329484a95c) to Topeka.
Unfortunately this results in a conflict with your pull request.

**Comment by ShreyashPromact** [comment]
@keyboardsurfer 
So, Should I again do PR and commit the changes? Or that will gone resolved by you?

**Comment by keyboardsurfer** [comment]
Could you please either update this PR or create a new one on top of the current master?

**Comment by keyboardsurfer** [comment]
Continued in #35

**Pull request closed without merging**
