### PR TITLE
Use ActivityOptionsCompat in SignInActivity

### PR DESCRIPTION
**Pull request by ardock**
Use ActivityCompat to be compatible down to sdk version 14.

### CODE REVIEW

**Comment by keyboardsurfer** [comment]
Thanks for this PR. It was fixed within f84e273d3b2b8229d9a99bd71d4af48640bfed14

**Comment by ardock** [comment]
@keyboardsurfer It's not fixed, [see](https://github.com/googlesamples/android-topeka/blob/master/app/src/main/java/com/google/samples/apps/topeka/activity/SignInActivity.java#L33)

activityoptions error

activityoptions_lint

Anyway the value is always null.

**Comment by keyboardsurfer** [comment]
Sorry, my bad. This will be fixed with the next push from my machine.

**Comment by ardock** [comment]
Thanks for the updates.

**Pull request closed without merging**
