### PR TITLE
FIXED: Floating label overlaps username last initial on S2 API 19 (4.4.4) #44

### PR DESCRIPTION
**Pull request by piotrek1543**
Hi,

according to unsolved issue with small screen devices, I decided to fixed it in the best way I can.
After reading #44 issue, I run my Genymotion emulator: Samsung S2 - 4.1.1 - API 16, 480x800, 240dpi.

The login activity wasn't good looking as I excepted: 
<strong>BEFORE CHANGES:</strong>
<a href="http://pl.tinypic.com?ref=2ahz6uo" target="_blank">Image and video hosting by TinyPic</a>&nbsp;&nbsp;<a href="http://pl.tinypic.com?ref=13zycms" target="_blank">Image and video hosting by TinyPic</a>

After putting a few small changes the look of sign in activity is:
<strong>AFTER CHANGES:</strong>
<a href="http://pl.tinypic.com?ref=o8yk38" target="_blank">Image and video hosting by TinyPic</a>&nbsp;&nbsp;<a href="http://pl.tinypic.com?ref=tarho6" target="_blank">Image and video hosting by TinyPic</a>

Some more useful information about improving layout on devices with older version of Android: #47 

Wish this would help.
Cheers.

### CODE REVIEW

**Comment by keyboardsurfer** [comment]
Thanks for this contribution.
Before I go into the code, re-apply the original formatting to it.
It's no fun hunting all the differences like this.

**Comment by piotrek1543** [comment]
I don't know why my xml files were so different, but I changed them.

It's no fun hunting all the differences like this. - notice, that there are only two XML files with some small changes. 

It's not brandly new Java classes with huge amount of code or a new functionality :-)

**Comment by keyboardsurfer** [comment]
Taking a look at the [file diff](https://github.com/googlesamples/android-topeka/pull/54/files), the formatting does not match the repository style.

**Comment by keyboardsurfer** [comment]
topeka_fix_signin

Is what we're looking for. I'll release it with the next push.

**Comment by piotrek1543** [comment]
Did you notice last screenshot? How far is it what you "expect".
Well, I'm trying to help, but I really don't get it why you do what you do.
Now I made decision to stop making issues and PR. Keep it calm...

**Comment by keyboardsurfer** [comment]
I feel sorry that you have made the decision to not make more contributions,
as they helped to improve the project. Please excuse if I came across rough.

To answer your question towards this PR:
Comparing the two relevant screenshots [side](https://camo.githubusercontent.com/10e18a8d703ec62a6d016e6696c96e5e7e41c657/687474703a2f2f6936362e74696e797069632e636f6d2f31337a79636d732e706e67) by [side](https://camo.githubusercontent.com/d0798b817a91a7d4d757bd0606372571fcdba0d5/687474703a2f2f6936342e74696e797069632e636f6d2f746172686f362e706e67) shows massive changes in paddings over the whole screen. It also introduces a new cropping issue in the top row of avatars.

I agree that this PR is a relatively small change. A total of 8 line changes can resolve the issue. Changing the formatting for the involved files resulted in a total of 110 changed lines in this [PR](https://github.com/googlesamples/android-topeka/pull/54/files).

**Comment by piotrek1543** [comment]
Right, you can play rough, because, you're Googler and much more experienced developer. I'm a guy, who started a Green Robot journey and some things still sounds strange to me.

In few weeks would learn more about coding formats, good practices from tutorials like this:
https://source.android.com/source/code-style.html (Have you known any good resources about that?)
and only after this path, I would open next PR or issue on any googlesamples repo.

Please re-read all closed issues and PR - I think there are still some things you missed before.

According to this PR - yes I changed padding quite a lot.
I added padding to activity signIn XML file. Notice, that there weren't any pads before.

**Comment by keyboardsurfer** [comment]
For a guided start, consider taking the [Android Fundamentals](https://www.udacity.com/course/developing-android-apps--ud853) Udacity course,
which will walk you through the process of developing an app.
The course material is accessible for free.

Of course you can always take a look into the [documentation of Android](http://developer.android.com/develop/index.html) as well.

Adding to that I also recommend participating in developer communities, such as [GDGs](https://developers.google.com/groups/directory/).

**Comment by piotrek1543** [comment]
@keyboardsurfer , thanks :-)

**Pull request closed without merging**
