### PR TITLE
Move animators and transitions to the correct v21 res folder and fix text appearance

### LINKED ISSUE #46: Score and answer items text appearance need be fixed for pre-lollipop devices
Lint detects usage of v21 resources on pre-lollipop devices:
1. Animators using interpolators only used on v21, can be moved to animator-v21.
2. Same for transitions, only used on v21, can be moved to transitions-v21 to avoid lint errors.
3. List items need to use Appcompat, currently using Material Theme only avalaible on API 21+.
cb3b
bc3c

Used here:
bc3

Solution for ListItem:
bc3d
bc3e

Workaround for ListItemSecondary, currently not included in AppCompat, use directly Body1:
bc3f

### PR DESCRIPTION
**Pull request by ardock**
Fixes #46 
Avoid lint errors about animators and transitions moving the resources to the respective v21 folders.
Improve the text appearance of list items for scores and answers and avoid lint errors.
Add and use the Topeka styles that inherit from the correct AppCompat styles.

It's safe move the animators and transitions, only used on API21+.
All the changes pass the tests, and scores and answers look better using the correct text size.

### CODE REVIEW

**Comment by piotrek1543** [comment]
@keyboardsurfer, please close pull requests if you thinks they're bad

**Comment by keyboardsurfer** [comment]
Thanks for reminding me on good etiquette, @piotrek1543. I do react on contributions in my own pace. Making assumptions on my behalf is not going to get discussions or pull requests anywhere.

**Comment by piotrek1543** [comment]
@keyboardsurfer, good ethic? Well. I don't know what do you mean exactly by this? I said (or I would say) only that it'd be nice to said like this "Hi @ardock, thanks for your PR. I would check it in few days."
Don't get angry by this.
 Please delete your comment. After this I would delete this one.

**Comment by piotrek1543** [comment]
@keyboardsurfer teach yourself guy :-p

**Comment by piotrek1543** [comment]
@keyboardsurfer, could you answer my request, please?

**Comment by keyboardsurfer** [comment]
@ardock: agreed. I'll check on it next week. Thanks for the PR.

**Comment by piotrek1543** [comment]
@keyboardsurfer, :+1:

**Comment by ardock** [comment]
Thanks guys, but I don't expect nothing when I create a pull request. You do not worry about me.

Feedback is welcome but I normally create it because  it's easier for me to integrate future additions.

In this case, I integrated it into a legacy educational project, refactored it a lot, and it's hard to do it.

Thanks for share comments and code, I'll follow creating pull requests but I won't comment anymore.

I'm not fluent in English, so i'll try to avoid this type of situations in the future, it's not good for nobody.

Sometimes I reuse rejected commits, dont feel you wasted your time when nobody answers you.

The other day you wrote on my no related and closed issues from last year, that was strange for me.

I instantly leave Telegram/Whatssap groups when my friends create them, think about those forks.

They are representing and working for big companies, and sometimes they feel like this

napalm_morning

I did a mistake commenting on your PR the other day, I'm sorry, I'm a solo developer and I was bored.

I really don't recommend now that company for an android developer because they currently don't understand our needs, it's only a beta, and I'm waiting for a publicly available Google solution for that, we need it.

I simply learned to use it because I forked that project last year and they used it, another mistake.

I don't think they use it internally, and it's not necessary for other PR, don't ask to include it please.

That was not the idea, I only thought that your PR perhaps would break mine and I didn't understand it.

I use services like Bitbucket for my private projects and I only use Github Google samples for practice other services and try to contribute.

I'm going to close the PRs because are not vital, the project works without them, simply mine looks better :smile_cat:

**Comment by keyboardsurfer** [comment]
:+1: to it looks better with this PR's changes in the codebase.
I very much appreciate your help in improving the way the code is structured.
I have not come around to merge them before the weekend.

**Comment by keyboardsurfer** [comment]
Again, thanks a lot for your contribution.

**Comment by ardock** [comment]
Thanks for solve the lint warnings, easier to detect real problems now :+1: 

Remember that the floating label still overlaps the username initial in pre-lollipop devices.

I was worried about that try catch api 19 but is my min SDK version.

I'm going to use [this](http://blog.raffaeu.com/archive/2015/04/11/android-and-the-transparent-status-bar.aspx) for the color of the Kitkat status bar and I solved the status bar errors like this:

```
    <style name="Base.Topeka" parent="Theme.AppCompat.Light.NoActionBar">
        <item name="android:textColorPrimaryInverse">@color/text_light</item>
        <item name="android:textColor">@color/text_dark</item>
        <item name="android:radioButtonStyle">@style/Topeka.CompoundButton.Radio</item>
        <item name="android:buttonStyle">@style/Topeka.CompoundButton</item>
        <item name="android:colorBackground">@color/light_grey</item>
    </style>

    <style name="Topeka" parent="Base.Topeka.Default" />
    <style name="Base.Topeka.Default">
        <item name="colorPrimary">@color/topeka_primary</item>
        <item name="colorPrimaryDark">@color/topeka_primary_dark</item>
        <item name="android:textColorPrimary">@android:color/black</item>
        <item name="android:windowBackground">@color/light_grey</item>
        <item name="colorAccent">@color/topeka_accent</item>
    </style>

    <style name="Topeka.Blue" parent="Base.Topeka.Blue" />
    <style name="Base.Topeka.Blue">
        <item name="colorPrimary">@color/theme_blue_primary</item>
        <item name="colorPrimaryDark">@color/theme_blue_primary</item>
        <item name="android:textColorPrimary">@color/theme_blue_text</item>
        <item name="android:windowBackground">@color/theme_blue_background</item>
        <item name="colorAccent">@color/theme_blue_accent</item>
    </style>
```
v21... (so other files were not affected. You are more lazy :smile_cat: )
```
    <style name="Topeka" parent="Base.Topeka.Default">
        <item name="android:windowDrawsSystemBarBackgrounds">true</item>
        <item name="android:windowContentTransitions">true</item>
        <item name="android:statusBarColor">@color/topeka_primary_dark</item>
    </style>

    <style name="Topeka.Blue" parent="Base.Topeka.Blue">
        <item name="android:statusBarColor">@color/theme_blue_primary_dark</item>
    </style>
```
I needed to refactor the DBHelper into three classes and to solve cyclic dependencies to integrate it in a layered project.

I know you dont need it but you can try it or integrate it with firebase, thanks for share, learning a lot.

**Comment by piotrek1543** [comment]
@ardock said: Remember that the floating label still overlaps the username initial in pre-lollipop devices.

For me, it's only a small screen size issue, but in a fact many cheap smartphones has small screens, co let's say you're right :-)

**Comment by piotrek1543** [comment]
@ardock which phone did you used to find this issue. I'm gonna make an emulator or find a phone with exactly or similar parameters and fix this issue on my own

**Comment by ardock** [comment]
@piotrek1543 Is a Samsung Galaxy S2 running Android KitKat 4.4.4 (ROM released by Cyanogen Team, CM11)

[Dimensiones	125.3 mm (4.93 in) H,66.1 mm (2.60 in) W,8.49 mm (0.334 in)](https://es.wikipedia.org/wiki/Samsung_Galaxy_S_II)

Android Studio templates (login one) use this view without adding paddings and looks good.

**Comment by piotrek1543** [comment]
@ardock , haha... I have a S2 with Cyanogenmod 12.1 and I have this issue, so it depends on screen not Android version.

Later I would try to fix it.

**Comment by ardock** [comment]
@piotrek1543 hehe l was waiting the fix for answer. It was not a cheap mobile, I love it. I used s2 for a year after to buy the nexus5, using the last one only for testing. My friends didn't understand it. I really didn't need a change.

Now that you finished your training with keyboardsurfer, less testing and more fixes, my semi-initial still there :smile:

**Comment by piotrek1543** [comment]
@ardock, sorry, but learning Espresso testesting was so addictive :-D 
Did you find any way to fix that issue?

**Comment by ardock** [comment]
I deleted the paddings as you know and waiting an altenative, I have other addictions too.

**Comment by piotrek1543** [comment]
@ardock your "final" version of android-topeka is on your Github profile or you have this on private repo on BitBucket?

**Comment by ardock** [comment]
@piotrek1543 Thanks for the fix :+1: 

If you talk to me directly I feel bad when I don't answer but I feel the same when I do it due to the forks.

It's on Bitbucket, but nothing interesting for other there. On github only ci experiments because is free.

I opened the issues section on my fork, next time you want to talk to me directly, we do there so we don't disturb other.

**Comment by piotrek1543** [comment]
@ardock ok, thanks.

**Pull request merged**
