### PR TITLE
fix: QuizActivity restore problem

### PR DESCRIPTION
**Pull request by CharlesLee-Ice**
When QuizActivity was recycled and restored after user has selected an answer, new QuizActivity will not show up the selected option.

### CODE REVIEW

**Comment by CharlesLee-Ice** [comment]
I signed it!

**Comment by keyboardsurfer** [comment]
Please make sure to follow the link and sign the Google CLA. Before this has been done successfully I am unable to accept any contributions from you for this project.

**Comment by keyboardsurfer** [comment]
Also please add some more context to the problem you're solving with this pull request.

**Comment by CharlesLee-Ice** [comment]
I signed it!

**Pull request closed without merging**
