### PR TITLE
Several fixes

### PR DESCRIPTION
**Pull request by shchurov**
Default avatar was set automatically but wasn't highlighted. Also selected avatar wasn't retained across config changes, it required to rewrite some logic around checking items within GridView. I think `choiceMode="singleChoice"` is a good approach.

### CODE REVIEW

**Comment by shchurov** [comment]
Updated with fixes.

**Comment by shchurov** [comment]
Pushed few more fixes:
1. There was an issue with lastInitial EditText, it shows only one symbol, however if you keep typing and then try to delete the input - you have to delete all the symbols you've typed.
2. Blinking of app content and navigation/status bar during the transition from SignInFragment to CategorySelectionActivity. The fix is a little tricky, however finishAfterTransition() didn't work - it called finish() immediately.
3. I noticed that when you click Sign Out in CategorySelectionActivity, it takes significant time for the app to get back to SignInActivity. I found out that preFillDatabase() consumes about 1 sec. Wrapping all the operations with transaction worked out.

**Comment by keyboardsurfer** [comment]
I've squashed the first two commits to e92fd0a60c39728f7acd9e9a76d2db4e29352fed and released them already. I'll take a look at 5e91022eed6b37642129b38122cf2f587cced937 later on.

**Comment by keyboardsurfer** [comment]
5e91022eed6b37642129b38122cf2f587cced937 has been made obsolete by 9872032bbdbf9fdfc0bd60531bf204317ada5b4c. Thanks for bringing this to my attention.

**Comment by shchurov** [comment]
Pushed database issue fix

**Comment by keyboardsurfer** [comment]
Cherry picked onto master. Thanks a lot for your contributions!

**Pull request closed without merging**
