### PR TITLE
Adding floating layouts effect to "Sign In" layout. Updating build.gradle file.

### PR DESCRIPTION
**Pull request by piotrek1543**

### CODE REVIEW

**Comment by keyboardsurfer** [comment]
I don't see how this adds any value when you don't add any features at the same time.

**Comment by piotrek1543** [comment]
@keyboardsurfer, newest dependencies sometimes fix the issue of older, but of course I can add some more commits with features or add some improvements :-) 
 
Please, don't close this PR and I will add in next few days some goods to improve this nice app.

**Comment by piotrek1543** [comment]
@keyboardsurfer  Hi, please check new effect and please add some thoughts about it :+1:

**Comment by keyboardsurfer** [comment]
Thanks for this contribution. I've [implemented this](https://github.com/googlesamples/android-topeka/blob/master/app/src/main/res/layout/sign_in_username.xml#L37) in the most recent release as well.

**Comment by piotrek1543** [comment]
@keyboardsurfer  so another commit unnecessary. 
Maybe this is time to close it :-/

**Pull request closed without merging**
