### PR TITLE
Fix SignIn fragment and tests and consider all the player preferences required

### LINKED ISSUE #58: The app crashes due to missing Test annotation and latest avatar selection changes
This test was not annotated:

```
com.google.samples.apps.topeka.activity.SignInActivityTest > signIn_performSignIn[Nexus 5 - 6.0] FAILED
        android.support.test.espresso.PerformException: Error performing 'single click' on view 'with id: com.google.samples.apps.topeka:id/done'.
        at android.support.test.espresso.PerformException$Builder.build(PerformException.java:83)
```

We can add a default avatar but then a new test would fail:

```
com.google.samples.apps.topeka.activity.SignInActivityTest > avatar_noneChecked[Nexus 5 - 6.0] FAILED
        android.support.test.espresso.base.DefaultFailureHandler$AssertionFailedWithCauseError: 'not with checkbox state: is <true>' doesn't match the selected view.
        Expected: not with checkbox state: is <true>
```

These latest changes and the next method seem to consider all the preferences required:

```
    /**
     * Check whether a user is currently signed in.
     *
     * @param context The context to check this in.
     * @return <code>true</code> if login data exists, else <code>false</code>.
     */
    public static boolean isSignedIn(Context context) {
        final SharedPreferences preferences = getSharedPreferences(context);
        return preferences.contains(PREFERENCE_FIRST_NAME) &&
                preferences.contains(PREFERENCE_LAST_INITIAL) &&
                preferences.contains(PREFERENCE_AVATAR);
    }
```

So getPlayer needs to be stricter and change `&&` by `||` like this:

```
        if (null == firstName || null == lastInitial || null == avatar) {
```

Otherwise I think would be possible to be signed in and be considered signed out in some places.

The textWatcher currently only detects that one editText contains text.

It's necessary to only show the mFabDone when an avatar is selected and both editText contain text.

I added tests that detect these issues and offer a possible solution to fix it:

```
com.google.samples.apps.topeka.activity.SignInActivityTest > signIn_withoutFirstNameFailed[Nexus 5 - 6.0] FAILED
        android.support.test.espresso.base.DefaultFailureHandler$AssertionFailedWithCauseError: 'not is displayed on the screen to the user' doesn't match the selected view.
        Expected: not is displayed on the screen to the user

com.google.samples.apps.topeka.activity.SignInActivityTest > signIn_withoutLastInitialFailed[Nexus 5 - 6.0] FAILED
        android.support.test.espresso.base.DefaultFailureHandler$AssertionFailedWithCauseError: 'not is displayed on the screen to the user' doesn't match the selected view.
        Expected: not is displayed on the screen to the user

com.google.samples.apps.topeka.activity.SignInActivityTest > signIn_withoutAvatarFailed[Nexus 5 - 6.0] FAILED
        android.support.test.espresso.base.DefaultFailureHandler$AssertionFailedWithCauseError: 'not is displayed on the screen to the user' doesn't match the selected view.
        Expected: not is displayed on the screen to the user

11-18 13:46:51.797 25212-25212/com.google.samples.apps.topeka 
E/AndroidRuntime: FATAL EXCEPTION: main
 Process: com.google.samples.apps.topeka, PID: 25212
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.Enum.name()' on a null object reference
    at com.google.samples.apps.topeka.helper.PreferencesHelper.writeToPreferences(PreferencesHelper.java:49)
    at com.google.samples.apps.topeka.fragment.SignInFragment.savePlayer(SignInFragment.java:238)
    at com.google.samples.apps.topeka.fragment.SignInFragment.access$200(SignInFragment.java:48)
    at com.google.samples.apps.topeka.fragment.SignInFragment$3.onClick(SignInFragment.java:161)
    at android.view.View.performClick(View.java:5198)
    at android.view.View$PerformClick.run(View.java:21147)
    at android.os.Handler.handleCallback(Handler.java:739)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:148)
    at android.app.ActivityThread.main(ActivityThread.java:5417)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

```

### PR DESCRIPTION
**Pull request by ardock**
This fixes #58 

Added missing Test annotation and new tests to improve SignIn behavior and avoid crashes.
Now the SignInFragment mDoneFab requires all the player preferences to be shown to pass tests.
If any player preference is missing, getPlayer method returns null.

### CODE REVIEW

**Comment by ardock** [comment]
I copy pasted the name of my avatar cat inspired in a fictional and famous manga character.
You can change it back to Zaphod B.

**Comment by ardock** [comment]
@keyboardsurfer Thanks for the comments, I created a new PR based on your suggestions.

**Comment by piotrek1543** [comment]
@ardock, please learn about 'squashing' commits. The easiest way you would find here:
http://blog.steveklabnik.com/posts/2012-11-08-how-to-squash-commits-in-a-github-pull-request

**Comment by ardock** [comment]
Thanks @piotrek1543, I never tried it in a PR, normally are ignored :), I will do it next time.

**Comment by piotrek1543** [comment]
@ardock, glad I could help. Nowadays I used that twice and it works good. 
Maybe if I knew it before, @keyboardsurfer wouldn't close at least one of my PRs :-D

**Comment by keyboardsurfer** [comment]
Awesome, thanks for the cleaned up PR and spotting the issue!

**Pull request merged**
